spring:
  data:
    mongodb:
      authentication-database: admin
      database: ktln-ecommerce
      host: localhost
      port: 27017
#      username:
#      password:
      auto-index-creation: true

#Email
  #
  mail:
    host: smtp.gmail.com
    port: 587
    username: quangdang2001.3@gmail.com
    password: jzseqkvlsmuzddyl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#Date time
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+7:00
    serialization:
      write_dates_as_timestamps: false

#Swagger
springdoc:
  swagger-ui:
    path=/swagger-ui:
      html: /swagger-ui.html

# LOCAL VARIABLE
cloudinary:
  cloud_name: quangdangcloud
  api_key: 738222114899535
  api_secret: V37UHtOmQ62U1VH-kXyd7kRLgf4


