spring:
  data:
    mongodb:
      authentication-database: admin
      database: KLTNEcommerce
      host: localhost
      port: 27017
      username: root
      password: 2211
      auto-index-creation: true


