spring:
  data:
    mongodb:
      authentication-database: admin
      database: ktln-ecommerce
      host: localhost
      port: 27017
      username: rootuser
      password: rootpass
      auto-index-creation: true

